name: avl
channels:
  - conda-forge
dependencies:
  - jupyterlab >=3
  - jupytext
  - python >=3.7
  - requests
  - coda
  - ipyleaflet-gl-vector-layer-plugin >=0.1.6
  - ipyleaflet
  - harp
  - panel
  - pyproj
  - vtk >=9.1
  - plotly
  - numpy
  - scipy
  - matplotlib-base
  - cmcrameri
