name: avl
channels:
  - conda-forge
dependencies:
  - python>=3.7
  - coda
  - ipyleaflet>=0.13.5, <0.17
  - ipyleaflet-gl-vector-layer-plugin
  - matplotlib
  - harp
  - panel
  - pyproj
  - vtk>=9.1
  - plotly
  - numpy
  - scipy
