name: avl-dev
channels:
  - conda-forge
dependencies:
  - cmcrameri
  - coda
  - harp
  - ipyleaflet
  - ipyleaflet-gl-vector-layer-plugin >=0.1.6
  - jupyterlab >=3
  - jupytext
  - matplotlib-base
  - numpy
  - panel
  - plotly
  - pyproj
  - python >=3.7
  - requests
  - scipy
  - vtk >=9.1
